spring:
  main:
    lazy-initialization: false
    banner-mode: off
  application:
    name: tcrm
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategySnakeCaseImpl
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

springdoc:
  show-actuator: false
  swagger-ui:
    enabled: true # for a while

logging:
  level:
    org.springframework: INFO

server:
  port: 8080
  tomcat:
    connection-timeout: 5s

jwt:
  access-token:
    secret: ${JWT_ACCESS_SECRET}
    exp_time: ${JWT_ACCESS_EXP_TIME}
  refresh-token:
    secret: ${JWT_REFRESH_SECRET}
    exp_time: ${JWT_REFRESH_EXP_TIME}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
  allowed-methods: ${CORS_ALLOWED_METHODS}
  allowed-headers: ${CORS_ALLOWED_HEADERS}
  allow-credentials: ${CORS_ALLOW_CREDENTIALS}

app:
  base-url: "http://domain-name"
  admin-uuid: "de40eacb-7f13-4165-ba80-cf7a65f2e490"
  files:
    upload-path: "/app/static/uploads/"
  email:
    from: "no-reply@exapmle.com"
  template:
    email-verification: "email-verification"
    notification: "notification"
    remind: "remind"
  telegram-service:
    url: "telegram-api:8001"
