spring:
  main:
    lazy-initialization: false
    banner-mode: off
  application:
    name: tcrm
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.yml
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategySnakeCaseImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  show-actuator: true

logging:
  level:
    org.springframework: INFO

server:
  port: 8080


jwt:
  access-token:
    secret: ${JWT_ACCESS_SECRET:57947d179f76e6eb61b2cbc91bc693ed70f630b8a007a5f4a2703124cb66b089} # not actual secret
    exp_time: ${JWT_ACCESS_EXP_TIME:900000000}
  refresh-token:
    secret: ${JWT_REFRESH_SECRET:12f0e9d76988656e95a02181584ba59e2efe2a94f80e92dc9d5e65723eeec682} # not actual secret
    exp_time: ${JWT_REFRESH_EXP_TIME:900000000}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:*}
  allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS}
  allowed-headers: ${CORS_ALLOWED_HEADERS:*}
  allow-credentials: ${CORS_ALLOW_CREDENTIALS:false}


app:
  base-url: "http://localhost/api/v1"
  admin-uuid: "de40eacb-7f13-4165-ba80-cf7a65f2e490"
  files:
    upload-path: "/app/static/uploads/"
  email:
    from: "no-reply@exapmle.com"
  template:
    email-verification: "email-verification"
    notification: "notification"
    remind: "remind"
  telegram-service:
    url: "localhost:8001"
